apiVersion: messaging.kb.lorenzodeluca.it/v1alpha1
kind: DataStream
metadata:
  name: datastream-sample
  namespace: default
spec:
  topicName: kb-user-telemetry-data
  partitions: 2
  replicationFactor: 1
