apiVersion: kafka.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kafka-default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: kafka-credentials
      key: credentials
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-default
spec:
  credentials:
    source: InjectedIdentity
