# This RoleBinding "attaches" the Role permissions to a specific ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # Name of this binding object.
  name: provider-kubernetes-manager-binding

  # Namespace where the Role is defined and where permissions apply.
  namespace: default

subjects:
  - kind: ServiceAccount
    # ServiceAccount of provider-kubernetes controller pod.
    name: provider-kubernetes-4c9c004f2f1e
    # Namespace where provider-kubernetes runs.
    namespace: upbound-system

roleRef:
  # roleRef points to the Role being granted.
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: provider-kubernetes-manager
